### ISSUE TITLE
Line 46 %XMLRoot% := XA_XMLToArray(XMLObj.childNodes)

### ISSUE THREAD

**Issue by cdmlaracha** [hi5/XA#2]
Is the variable enclosed in% on line 46 correct? The only way the code works for me is by removing those characters from%.
Maybe it's my fault. 

My code:

`#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#Include xa.ahk

xml := Object()
xml := XA_Load("dev.xml")
if (xml == 1){
	MsgBox % "Error loading XML file."
}`

the xml variable gave me a value 'document' that I don't understand and can't manipulate.

Sorry if I waste your time.

**Comment by hi5** [comment]
Yes as that returns the "nodeName" - in the examples in the readme `MyArray1` and `MyArray2` 
XA is meant to store/restore AutoHotkey arrays, not random XML data, perhaps something is incorrect with your XML file.
Try the posted examples from the readme

**Comment by cdmlaracha** [comment]
I understand. I have tried using XA to load an XML that is not generated from AHK or from the XA utility.
I'm dumb. Sorry, thanks for responding so quickly.
I'm saving this for another time.
Thank you very very much!!!

**Comment by hi5** [comment]
You can use `ComObjCreate("MSXML2.DOMDocument.6.0")` to read an XML file, sample script https://www.autohotkey.com/boards/viewtopic.php?p=282978
